#!/bin/sh
PATH="/usr/bin:/usr/sbin:/bin:/sbin"

# We check for this file after receiving a SIGCONT to move to stage3
chmod 100 /run/runit/stopit

# We check for this file in stage3 to halt or reboot
chmod 100 /run/runit/reboot

# Proceed with shutdown process
printf 'System is going down...\n' | wall
